# 선문대학교 컴퓨터공학부
# 2022243101 최완우

### 학력, 교육 연수, 혼인 상태, 직업 정보를 담은 연봉 데이터셋을 이용해 연봉을 예측하라.

데이터셋 : 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/salary.csv'

# 2. 라이브러리 및 데이터 불러오기

In [65]:
# 필수 모듈과 데이터 파일 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/salary.csv'
data = pd.read_csv(file_url, skipinitialspace = True)

In [66]:
# 데이터 살펴보기
data = pd.read_csv(file_url, skipinitialspace = False)
data

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,NaN,Some-college,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [67]:
# class 고윳값 및 특징 확인하기
data['class'].unique()

<StringArray>
[' <=50K', ' >50K']
Length: 2, dtype: str

In [68]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       46043 non-null  str
 2   education       48842 non-null  str
 3   education-num   48842 non-null  int64
 4   marital-status  48842 non-null  str
 5   occupation      46033 non-null  str
 6   relationship    48842 non-null  str
 7   race            48842 non-null  str
 8   sex             48842 non-null  str
 9   capital-gain    48842 non-null  int64
 10  capital-loss    48842 non-null  int64
 11  hours-per-week  48842 non-null  int64
 12  native-country  47985 non-null  str
 13  class           48842 non-null  str
dtypes: int64(5), str(9)
memory usage: 5.2 MB

In [69]:
# 통계 정보 출력 - int64 변수만 출력
data.describe()

                age  education-num  capital-gain  capital-loss  hours-per-week
count  48842.000000   48842.000000  48842.000000  48842.000000    48842.000000
mean      38.643585      10.078089   1079.067626     87.502314       40.422382
std       13.710510       2.570973   7452.019058    403.004552       12.391444
min       17.000000       1.000000      0.000000      0.000000        1.000000
25%       28.000000       9.000000      0.000000      0.000000       40.000000
50%       37.000000      10.000000      0.000000      0.000000       40.000000
75%       48.000000      12.000000      0.000000      0.000000       45.000000
max       90.000000      16.000000  99999.000000   4356.000000       99.000000

In [70]:
# 통계 정보 출력 - object 형까지 출력
data.describe(include = 'all')

,age,workclass,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
count,48842.000000,46043,48842,48842.000000,48842,46033,48842,48842,48842,48842.000000,48842.000000,48842.000000,47985,48842
unique,NaN,8,16,NaN,7,14,6,5,2,NaN,NaN,NaN,41,2
top,NaN,Private,HS-grad,NaN,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,NaN,NaN,United-States,<=50K
freq,NaN,33906,15784,NaN,22379,6172,19716,41762,32650,NaN,NaN,NaN,43832,37155
mean,38.643585,NaN,NaN,10.078089,NaN,NaN,NaN,NaN,NaN,1079.067626,87.502314,40.422382,NaN,NaN
std,13.710510,NaN,NaN,2.570973,NaN,NaN,NaN,NaN,NaN,7452.019058,403.004552,12.391444,NaN,NaN
min,17.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,NaN,NaN
25%,28.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
50%,37.000000,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
75%,48.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,45.000000,NaN,NaN
max,90.000000,NaN,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,99999.000000,4356.000000,99.000000,NaN,NaN

# 3.1 전처리 : 범주형 데이터

In [71]:
data['class'] = data['class'].map({'<=50K': 0, '>50K': 1})
data['class']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
48837   NaN
48838   NaN
48839   NaN
48840   NaN
48841   NaN
Name: class, Length: 48842, dtype: float64

In [72]:
# object 형 변수를 따로 리스트에 저장
obj_list = []
for i in data.columns :
    if data[i].dtype == 'object' :
        obj_list.append(i)
        
obj_list

[]

In [73]:
# 각 변수의 고윳값 개수 확인
for i in obj_list :
    print(i, data[i].nunique())

In [74]:
# education 과 education-num 변수
for i in np.sort(data['education-num'].unique()) :
    print(i, data[data['education-num'] == i]['education'].unique())

1 <StringArray>
[' Preschool']
Length: 1, dtype: str
2 <StringArray>
[' 1st-4th']
Length: 1, dtype: str
3 <StringArray>
[' 5th-6th']
Length: 1, dtype: str
4 <StringArray>
[' 7th-8th']
Length: 1, dtype: str
5 <StringArray>
[' 9th']
Length: 1, dtype: str
6 <StringArray>
[' 10th']
Length: 1, dtype: str
7 <StringArray>
[' 11th']
Length: 1, dtype: str
8 <StringArray>
[' 12th']
Length: 1, dtype: str
9 <StringArray>
[' HS-grad']
Length: 1, dtype: str
10 <StringArray>
[' Some-college']
Length: 1, dtype: str
11 <StringArray>
[' Assoc-voc']
Length: 1, dtype: str
12 <StringArray>
[' Assoc-acdm']
Length: 1, dtype: str
13 <StringArray>
[' Bachelors']
Length: 1, dtype: str
14 <StringArray>
[' Masters']
Length: 1, dtype: str
15 <StringArray>
[' Prof-school']
Length: 1, dtype: str
16 <StringArray>
[' Doctorate']
Length: 1, dtype: str

In [75]:
# education 변수는 제거
data.drop('education', axis = 1, inplace = True)

In [76]:
# occupation 변수 처리
data['occupation'].value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [77]:
# native-country 변수 처리
data['native-country'].value_counts()

native-country
United-States                 43832
Mexico                          951
Philippines                     295
Germany                         206
Puerto-Rico                     184
Canada                          182
El-Salvador                     155
India                           151
Cuba                            138
England                         127
China                           122
South                           115
Jamaica                         106
Italy                           105
Dominican-Republic              103
Japan                            92
Guatemala                        88
Poland                           87
Vietnam                          86
Columbia                         85
Haiti                            75
Portugal                         67
Taiwan                           65
Iran                             59
Nicaragua                        49
Greece                           49
Peru                             46
Ecuador                          45
France                           38
Ireland                          37
Thailand                         30
Hong                             30
Cambodia                         28
Trinadad&Tobago                  27
Laos                             23
Yugoslavia                       23
Outlying-US(Guam-USVI-etc)       23
Scotland                         21
Honduras                         20
Hungary                          19
Holand-Netherlands                1
Name: count, dtype: int64

In [78]:
# 나라별 class 평균값 확인
data.groupby('native-country').mean(numeric_only = True).sort_values('class')

,age,education-num,capital-gain,capital-loss,hours-per-week,class
native-country,,,,,,
Cambodia,36.892857,9.392857,697.464286,194.821429,42.035714,NaN
Canada,44.049451,10.692308,1233.505495,131.159341,40.406593,NaN
China,41.852459,11.262295,1407.737705,170.655738,38.262295,NaN
Columbia,39.458824,9.258824,125.364706,65.247059,39.929412,NaN
Cuba,46.355072,9.391304,470.543478,62.717391,40.101449,NaN
Dominican-Republic,37.970874,7.320388,1064.456311,39.029126,41.621359,NaN
Ecuador,37.666667,9.244444,328.288889,0.000000,39.266667,NaN
El-Salvador,33.380645,6.722581,392.761290,36.367742,36.361290,NaN
England,40.527559,11.110236,1076.551181,108.913386,41.937008,NaN
France,40.315789,12.000000,417.473684,37.052632,42.789474,NaN
Germany,38.601942,10.927184,1062.058252,61.456311,40.815534,NaN
Greece,45.836735,9.755102,1131.448980,174.857143,46.897959,NaN
Guatemala,32.090909,6.306818,167.875000,18.113636,38.715909,NaN
Haiti,38.600000,8.533333,297.626667,66.200000,36.920000,NaN
Holand-Netherlands,32.000000,10.000000,0.000000,2205.000000,40.000000,NaN
Honduras,35.050000,8.350000,75.300000,152.000000,35.650000,NaN
Hong,34.233333,10.433333,500.800000,255.466667,40.266667,NaN
Hungary,50.368421,10.947368,490.315789,87.789474,37.947368,NaN
India,38.364238,12.536424,3196.390728,115.417219,41.423841,NaN
Iran,38.372881,12.186441,1490.169492,124.406780,42.949153,NaN
Ireland,38.486486,9.783784,494.783784,96.189189,42.432432,NaN
Italy,45.419048,8.790476,797.895238,52.638095,40.942857,NaN
Jamaica,37.141509,9.811321,495.915094,17.801887,39.160377,NaN
Japan,37.358696,11.423913,1874.586957,59.445652,42.282609,NaN
Laos,35.217391,8.826087,125.434783,75.652174,39.391304,NaN
Mexico,33.635121,6.026288,415.954784,32.656151,40.213460,NaN
Nicaragua,36.285714,9.000000,138.653061,69.938776,36.938776,NaN
Outlying-US(Guam-USVI-etc),38.826087,10.043478,0.000000,76.608696,41.347826,NaN
Peru,36.434783,9.826087,39.804348,40.173913,36.543478,NaN
Philippines,39.633898,10.722034,1508.823729,88.522034,39.620339,NaN
Poland,42.758621,10.068966,471.919540,70.390805,37.689655,NaN
Portugal,41.238806,6.761194,203.402985,0.000000,42.238806,NaN
Puerto-Rico,39.864130,8.331522,335.347826,104.777174,39.016304,NaN
Scotland,46.761905,10.190476,246.571429,0.000000,41.666667,NaN
South,38.095652,10.765217,1678.208696,134.269565,42.852174,NaN
Taiwan,34.184615,13.276923,1948.600000,121.476923,39.400000,NaN
Thailand,37.666667,10.833333,243.266667,49.500000,44.700000,NaN
Trinadad&Tobago,39.259259,8.962963,116.185185,156.518519,38.888889,NaN
United-States,38.698690,10.168667,1089.626529,88.789743,40.440774,NaN
Vietnam,34.616279,9.616279,604.802326,86.372093,37.976744,NaN
Yugoslavia,40.478261,9.391304,916.391304,0.000000,40.217391,NaN

In [79]:
# native-country(범주형)를 국가별 class 평균(숫자)로 치환
data['native-country'] = data['native-country'].map(
    data.groupby('native-country')['class'].mean()
)
data

,age,workclass,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,class
0,25,Private,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,NaN,NaN
1,38,Private,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,NaN,NaN
2,28,Local-gov,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,NaN,NaN
3,44,Private,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,NaN,NaN
4,18,NaN,10,Never-married,NaN,Own-child,White,Female,0,0,30,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,NaN,NaN
48838,40,Private,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,NaN,NaN
48839,58,Private,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,NaN,NaN
48840,22,Private,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,NaN,NaN
48841,52,Self-emp-inc,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,NaN,NaN

# 3.2 전처리 : 결측치 처리 및 더비 변수 변환

In [80]:
# native-country 결측치 처리
data['native-country'] = data['native-country'].fillna(-99)

In [81]:
# workclass(범주형) 결측치 처리
data['workclass'].value_counts()

workclass
Private             33906
Self-emp-not-inc     3862
Local-gov            3136
State-gov            1981
Self-emp-inc         1695
Federal-gov          1432
Without-pay            21
Never-worked           10
Name: count, dtype: int64

In [82]:
data['workclass'] = data['workclass'].fillna('Private')

In [83]:
# occupation(범주형) 결측치 처리
data['occupation'].value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [84]:
data['occupation'] = data['occupation'].fillna('Unknown')

In [85]:
# 나머지 범주형 변수를 더미 변수로 변환
data = pd.get_dummies(data, drop_first = True)

# 4.1 모델링 및 평가하기

In [86]:
# 훈련셋과 시험셋 나누기
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.drop('class', axis = 1), data['class'],
                                                    test_size = 0.4, random_state = 100)

In [87]:
# 결정트리 모델 선택하기
from sklearn.tree import DecisionTreeClassifier

In [88]:
# 모델링 및 예측 하기
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
pred = model.predict(X_test)

ValueError: Input y contains NaN.

In [ ]:
# 정확도 확인하기
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

NameError: name 'pred' is not defined

# 7. 매개변수 튜닝

In [ ]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)
print("Train score : ", accuracy_score(y_train, train_pred), end = ' ')
print("Test score : ", accuracy_score(y_test, test_pred))

ValueError: Input y contains NaN.

# 9. Random Froest 모델로 연봉분류 예측

참고 : RF_GBT.pptx