# 선문대학교 컴퓨터공학부
# 2022243101 최완우

# 2. 라이브러리 및 데이터 불러오기, 데이터 확인하기

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/car.csv'
data = pd.read_csv(file_url)

In [15]:
data.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0

In [16]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           8128 non-null   str
 1   year           8128 non-null   int64
 2   selling_price  8128 non-null   int64
 3   km_driven      8128 non-null   int64
 4   fuel           8128 non-null   str
 5   seller_type    8128 non-null   str
 6   transmission   8128 non-null   str
 7   owner          8128 non-null   str
 8   mileage        7907 non-null   str
 9   engine         7907 non-null   str
 10  max_power      7913 non-null   str
 11  torque         7906 non-null   str
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), str(9)
memory usage: 825.6 KB

In [17]:
round(data.describe(), 2)

          year  selling_price   km_driven    seats
count  8128.00        8128.00     8128.00  7907.00
mean   2013.80      638271.81    69819.51     5.42
std       4.04      806253.40    56550.55     0.96
min    1983.00       29999.00        1.00     2.00
25%    2011.00      254999.00    35000.00     5.00
50%    2015.00      450000.00    60000.00     5.00
75%    2017.00      675000.00    98000.00     5.00
max    2020.00    10000000.00  2360457.00    14.00

# 3. 전처리 : 텍스트 데이터

### 3.1 engine 변수 처리하기

In [18]:
data['engine'].str.split(expand = True)

         0   1
0     1248  CC
1     1498  CC
2     1497  CC
3     1396  CC
4     1298  CC
...    ...  ..
8123  1197  CC
8124  1493  CC
8125  1248  CC
8126  1396  CC
8127  1396  CC

[8128 rows x 2 columns]

In [19]:
data[['engine', 'engine_unit']] = data['engine'].str.split(expand = True)

In [20]:
data['engine'].head()

0    1248
1    1498
2    1497
3    1396
4    1298
Name: engine, dtype: str

In [21]:
data['engine'] = data['engine'].astype('float32')

In [22]:
data['engine_unit'].unique()

<StringArray>
['CC', nan]
Length: 2, dtype: str

In [23]:
data.drop('engine_unit', axis = 1, inplace = True)

### 3.2 max_power 변수 처리하기

In [24]:
data[['max_power', 'max_power_unit']] = data['max_power'].str.split(expand = True)

In [25]:
data['max_power'].head()

0        74
1    103.52
2        78
3        90
4      88.2
Name: max_power, dtype: str

In [26]:
data[data['max_power'] == 'bhp']

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats,max_power_unit
4933,Maruti Omni CNG,2000,80000,100000,CNG,Individual,Manual,Second Owner,10.9 km/kg,796.0,bhp,NaN,8.0,NaN

In [27]:
def isFloat(value) :
    try :
        num = float(value)
        return num
    except ValueError :
        return np.nan

In [28]:
data['max_power'] = data['max_power'].apply(isFloat)

In [29]:
data['max_power'] = data['max_power'].astype('float32')

In [30]:
data['max_power_unit'].unique()

<StringArray>
['bhp', nan]
Length: 2, dtype: str

In [31]:
data.drop('max_power_unit', axis = 1, inplace = True)

### 3.3 mileage 변수 처리하기

In [32]:
data[['mileage', 'mileage_unit']] = data['mileage'].str.split(expand = True)

In [33]:
data['mileage'] = data['mileage'].astype('float32')

In [34]:
data['mileage_unit'].unique()

<StringArray>
['kmpl', 'km/kg', nan]
Length: 3, dtype: str

In [35]:
data['fuel'].unique()

<StringArray>
['Diesel', 'Petrol', 'LPG', 'CNG']
Length: 4, dtype: str

In [36]:
def mile(x) :
    if x['fuel'] == 'Petrol' :
        return x['mileage'] / 80.43
    elif x['fuel'] == 'Diesel' :
        return x['mileage'] / 73.56
    elif x['fuel'] == 'LPG' :
        return x['mileage'] / 40.85
    else :
        return x['mileage'] / 44.23

In [37]:
data['mileage'] = data.apply(mile, axis = 1)

In [38]:
data.drop('mileage_unit', axis = 1, inplace = True)

### 3.4 torque 변수 처리하기

In [39]:
data['torque'].head()

0              190Nm@ 2000rpm
1         250Nm@ 1500-2500rpm
2       12.7@ 2,700(kgm@ rpm)
3    22.4 kgm at 1750-2750rpm
4       11.5@ 4,500(kgm@ rpm)
Name: torque, dtype: str

In [40]:
data['torque'] = data['torque'].str.upper()

In [41]:
def torque_unit(x) :
    if 'NM' in str(x) :
        return 'Nm'
    elif 'KGM' in str(x) :
        return 'kgm'

In [42]:
data['torque_unit'] = data['torque'].apply(torque_unit)

In [43]:
data['torque_unit'].unique()

<StringArray>
['Nm', 'kgm', nan]
Length: 3, dtype: str

In [44]:
data[data['torque_unit'].isna()]['torque'].unique()

<StringArray>
[nan, '250@ 1250-5000RPM', '510@ 1600-2400', '110(11.2)@ 4800', '210 / 1900']
Length: 5, dtype: str

In [45]:
data['torque_unit'].fillna('Nm', inplace = True)

C:\Users\최완우\AppData\Local\Temp\ipykernel_16392\775739472.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data['torque_unit'].fillna('Nm', inplace = True)

0        Nm
1        Nm
2       kgm
3       kgm
4       kgm
       ...
8123     Nm
8124    kgm
8125     Nm
8126     Nm
8127     Nm
Name: torque_unit, Length: 8128, dtype: str

In [46]:
def split_num(x) :
    x = str(x)
    for i, j in enumerate(x) :
        if j not in '0123456789.' :
            cut = i
            break
    return x[:cut]

In [47]:
data['torque'] = data['torque'].apply(split_num)

In [48]:
data['torque']

0         190
1         250
2        12.7
3        22.4
4        11.5
        ...
8123    113.7
8124       24
8125      190
8126      140
8127      140
Name: torque, Length: 8128, dtype: str

In [49]:
data['torque'] = data['torque'].replace('', np.nan)

In [50]:
data['torque'] = data['torque'].astype('float64')

In [51]:
data['torque'].head()

0    190.0
1    250.0
2     12.7
3     22.4
4     11.5
Name: torque, dtype: float64

In [52]:
def torque_trans(x) :
    if x['torque_unit'] == 'kgm' :
        return x['torque'] * 9.8066
    else :
        return x['torque']

In [53]:
data['torque'] = data.apply(torque_trans, axis = 1)

In [54]:
data.drop('torque_unit', axis = 1, inplace = True)

In [55]:
data.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,0.318108,1248.0,74.000000,190.00000,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,0.287384,1498.0,103.519997,250.00000,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,0.220067,1497.0,78.000000,124.54382,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,0.312670,1396.0,90.000000,219.66784,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,0.200174,1298.0,88.199997,112.77590,5.0

### 3.5 name 변수 처리하기

In [56]:
data['name'] = data['name'].str.split(expand = True)[0]

In [57]:
data['name'].unique()

<StringArray>
[       'Maruti',         'Skoda',         'Honda',       'Hyundai',
        'Toyota',          'Ford',       'Renault',      'Mahindra',
          'Tata',     'Chevrolet',          'Fiat',        'Datsun',
          'Jeep', 'Mercedes-Benz',    'Mitsubishi',          'Audi',
    'Volkswagen',           'BMW',        'Nissan',         'Lexus',
        'Jaguar',          'Land',            'MG',         'Volvo',
        'Daewoo',           'Kia',         'Force',    'Ambassador',
         'Ashok',         'Isuzu',          'Opel',       'Peugeot']
Length: 32, dtype: str

In [58]:
data['name'] = data['name'].replace('Land', 'Land Rover')

## 3. 전처리 : 결측치 처리와 더미 변수 변환

In [59]:
data.isna().mean()

name             0.000000
year             0.000000
selling_price    0.000000
km_driven        0.000000
fuel             0.000000
seller_type      0.000000
transmission     0.000000
owner            0.000000
mileage          0.027190
engine           0.027190
max_power        0.026575
torque           0.027313
seats            0.027190
dtype: float64

In [60]:
data.dropna(inplace = True)

In [61]:
len(data)

7906

In [62]:
data = pd.get_dummies(data, columns = ['name', 'fuel', 'seller_type', 'transmission', 'owner'], drop_first = True)

In [63]:
data.head()

,year,selling_price,km_driven,mileage,engine,max_power,torque,seats,name_Ashok,name_Audi,...,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,2014,450000,145500,0.318108,1248.0,74.000000,190.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
1,2014,370000,120000,0.287384,1498.0,103.519997,250.00000,5.0,False,False,...,True,False,False,True,False,True,False,True,False,False
2,2006,158000,140000,0.220067,1497.0,78.000000,124.54382,5.0,False,False,...,False,False,True,True,False,True,False,False,False,True
3,2010,225000,127000,0.312670,1396.0,90.000000,219.66784,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
4,2007,130000,120000,0.200174,1298.0,88.199997,112.77590,5.0,False,False,...,False,False,True,True,False,True,False,False,False,False

## 4. 모델링 및 평가하기

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.drop('selling_price', axis=1), data['selling_price'], test_size=0.2, random_state=100)

In [66]:
from sklearn.ensemble import RandomForestRegressor

In [67]:
model = RandomForestRegressor(random_state = 100)
model.fit(X_train, y_train)
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

In [68]:
# RMSE를 사용해 평가
from sklearn.metrics import mean_squared_error
print('train_rmse : ', mean_squared_error(y_train, train_pred) ** 0.5, 'test_rmse : ', mean_squared_error(y_test, test_pred) ** 0.5)

train_rmse :  53531.41548125947 test_rmse :  131855.18391308116

## 6. 이해하기 : K-폴드 교차검증

In [69]:
from sklearn.model_selection import KFold

In [70]:
data

,year,selling_price,km_driven,mileage,engine,max_power,torque,seats,name_Ashok,name_Audi,...,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,2014,450000,145500,0.318108,1248.0,74.000000,190.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
1,2014,370000,120000,0.287384,1498.0,103.519997,250.00000,5.0,False,False,...,True,False,False,True,False,True,False,True,False,False
2,2006,158000,140000,0.220067,1497.0,78.000000,124.54382,5.0,False,False,...,False,False,True,True,False,True,False,False,False,True
3,2010,225000,127000,0.312670,1396.0,90.000000,219.66784,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
4,2007,130000,120000,0.200174,1298.0,88.199997,112.77590,5.0,False,False,...,False,False,True,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,2013,320000,110000,0.230014,1197.0,82.849998,113.70000,5.0,False,False,...,False,False,True,True,False,True,False,False,False,False
8124,2007,135000,119000,0.228385,1493.0,110.000000,235.35840,5.0,False,False,...,True,False,False,True,False,True,True,False,False,False
8125,2009,382000,120000,0.262371,1248.0,73.900002,190.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
8126,2013,290000,25000,0.320419,1396.0,70.000000,140.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
8127,2013,290000,25000,0.320419,1396.0,70.000000,140.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False

In [71]:
data.reset_index(drop = True, inplace = True)

In [72]:
data

,year,selling_price,km_driven,mileage,engine,max_power,torque,seats,name_Ashok,name_Audi,...,fuel_Diesel,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,2014,450000,145500,0.318108,1248.0,74.000000,190.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
1,2014,370000,120000,0.287384,1498.0,103.519997,250.00000,5.0,False,False,...,True,False,False,True,False,True,False,True,False,False
2,2006,158000,140000,0.220067,1497.0,78.000000,124.54382,5.0,False,False,...,False,False,True,True,False,True,False,False,False,True
3,2010,225000,127000,0.312670,1396.0,90.000000,219.66784,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
4,2007,130000,120000,0.200174,1298.0,88.199997,112.77590,5.0,False,False,...,False,False,True,True,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7901,2013,320000,110000,0.230014,1197.0,82.849998,113.70000,5.0,False,False,...,False,False,True,True,False,True,False,False,False,False
7902,2007,135000,119000,0.228385,1493.0,110.000000,235.35840,5.0,False,False,...,True,False,False,True,False,True,True,False,False,False
7903,2009,382000,120000,0.262371,1248.0,73.900002,190.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
7904,2013,290000,25000,0.320419,1396.0,70.000000,140.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False
7905,2013,290000,25000,0.320419,1396.0,70.000000,140.00000,5.0,False,False,...,True,False,False,True,False,True,False,False,False,False

In [73]:
kf = KFold(n_splits = 5)

In [74]:
X = data.drop('selling_price', axis = 1)
y = data['selling_price']

In [75]:
# 훈련셋과 시험셋 인덱스 확인
for i, j in kf.split(X) :
    print(i, j)

[1582 1583 1584 ... 7903 7904 7905] [   0    1    2 ... 1579 1580 1581]
[   0    1    2 ... 7903 7904 7905] [1582 1583 1584 ... 3160 3161 3162]
[   0    1    2 ... 7903 7904 7905] [3163 3164 3165 ... 4741 4742 4743]
[   0    1    2 ... 7903 7904 7905] [4744 4745 4746 ... 6322 6323 6324]
[   0    1    2 ... 6322 6323 6324] [6325 6326 6327 ... 7903 7904 7905]

In [76]:
train_rmse_total = []
test_rmse_total = []

In [77]:
# K 폴드 별로 모델링 및 예측, 평가
for train_index, test_index in kf.split(X) :
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model = RandomForestRegressor(random_state = 100)
    model.fit(X_train, y_train)
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    
    train_rmse = mean_squared_error(y_train, train_pred) ** 0.5
    test_rmse = mean_squared_error(y_test, test_pred) ** 0.5
    
    train_rmse_total.append(train_rmse)
    test_rmse_total.append(test_rmse)

In [78]:
train_rmse_total

[50825.5556350298,
 58854.04054344074,
 57904.19615940739,
 56218.23740006373,
 58967.150857632456]

In [84]:
print('train_rmse : ', sum(train_rmse_total) / 5, '\ntest_rmse : ', sum(test_rmse_total) / 5)

train_rmse :  66762.84568886801
test_rmse :  142205.83441414658

## 9.8 하이퍼파라미터 튜닝

In [81]:
train_rmse_total = []
test_rmse_total = []

for train_index, test_index in kf.split(X) :
    X_train, X_test = X.iloc[train_index, :], X.iloc[test_index, :]
    y_train, y_test = y[train_index], y[test_index]
    model = RandomForestRegressor(n_estimators = 300, max_depth = 50, min_samples_split = 5, n_jobs = -1, random_state = 100)
    model.fit(X_train, y_train)
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)
    
    train_rmse = mean_squared_error(y_train, train_pred) ** 0.5
    test_rmse = mean_squared_error(y_test, test_pred) ** 0.5
    
    train_rmse_total.append(train_rmse)
    test_rmse_total.append(test_rmse)

In [83]:
print('train_rmse : ', sum(train_rmse_total) / 5, '\ntest_rmse : ', sum(test_rmse_total) / 5)

train_rmse :  66762.84568886801
test_rmse :  142205.83441414658

In [88]:
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

model = SVR()
model.fit(X_train, y_train)
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)
print('train_rmse : ', mean_squared_error(y_train, train_pred) ** 0.5, 'test_rmse : ', mean_squared_error(y_test, test_pred) ** 0.5)

reg = Pipeline([
    ('scaler', StandardScaler()),
    ('svr', SVR())
])
reg.fit(X_train, y_train)
train_pred = reg.predict(X_train)
test_pred = reg.predict(X_test)
print('after scaling train_rmse : ', mean_squared_error(y_train, train_pred) ** 0.5, 'test_rmse : ', mean_squared_error(y_test, test_pred) ** 0.5)

train_rmse :  842944.6121590208 test_rmse :  815410.9128006144
after scaling train_rmse :  843042.709148349 test_rmse :  815508.8207408285

In [ ]:
import tensorflow as tf
from tensorflow import keras

model = keras.model.Sequential([
    keras.layers.Input(shape = (X_train.shape[1],)),
    keras.layers.Dense(128, activation = 'relu'),
    keras.layers.Dense(64, activation = 'relu'),
    keras.layers.Dense(32, activation = 'relu'),
    keras.layers.Dense(1)
])

model.compile(optimizer = 'adam', loss = 'mse')
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
history = model.fit(X_train_scaled, y_train, epochs = 100, validation_split = 0.2)